Program ini dibuat untuk melakukan pre-automation seperti eksplorasi data sederhana, data cleaning dan processing yang nantinya akan dikembangkan di data pipeline. Selanjutnya melakukan validasi data menggunakan Great Expectations, yang nantinya akan dilakukan automation menggunakan Airflow.

# Extract

In [1]:
import pandas as pd # import lib pandas

In [ ]:
df = pd.read_csv('data_raw.csv') # membaca file csv dengan nama data_raw.csv dan disimpan pada variabel df

In [3]:
df # menampilkan data df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,Cash,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,PayPal,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Credit Card,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,PayPal,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Bank Transfer,Store Pickup,No,No,33,Venmo,Quarterly

# EDA

In [4]:
df.info() # menampilkan struktur df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer ID               3900 non-null   int64
 1   Age                       3900 non-null   int64
 2   Gender                    3900 non-null   object
 3   Item Purchased            3900 non-null   object
 4   Category                  3900 non-null   object
 5   Purchase Amount (USD)     3900 non-null   int64
 6   Location                  3900 non-null   object
 7   Size                      3900 non-null   object
 8   Color                     3900 non-null   object
 9   Season                    3900 non-null   object
 10  Review Rating             3900 non-null   float64
 11  Subscription Status       3900 non-null   object
 12  Payment Method            3900 non-null   object
 13  Shipping Type             3900 non-null   object
 14  Discount Applied          3900 non-null   object
 15  Promo Code Used           3900 non-null   object
 16  Previous Purchases        3900 non-null   int64
 17  Preferred Payment Method  3900 non-null   object
 18  Frequency of Purchases    3900 non-null   object
dtypes: float64(1), int64(4), object(14)
memory usage: 579.0+ KB

Terdapat 3900 row dan 19 column, dengan tidak ada nilai null pada setiap column (alias bersih dari null). Terdapat 1 tipe float yaitu pada column Review Rating, 4 tipe Integer pada column Customer ID, Age, Purchase Amount (USD), dan Previous Purchases.

In [ ]:
df['Purchase Amount (USD)'].unique() # menampilkan nilai unik pada column Purchase Amount (USD), untuk melakukan sample pengecekan nilai null maupun whtie space.

array([ 53,  64,  73,  90,  49,  20,  85,  34,  97,  31,  68,  72,  51,
        81,  36,  38,  48,  62,  37,  88,  22,  25,  56,  94,  79,  67,
        91,  33,  69,  45,  60,  76,  39, 100,  21,  43,  54,  55,  30,
        28,  59,  24,  83,  46,  70,  29,  26,  58,  96,  40,  32,  95,
        41,  47,  99,  87,  92,  98,  89,  35,  75,  65,  86,  84,  77,
        27,  23,  74,  80,  42,  61,  82,  78,  93,  50,  57,  66,  44,
        52,  71,  63], dtype=int64)

In [ ]:
df['Location'].unique() # menampilkan nilai unik pada column Location, untuk melakukan sample pengecekan nilai null maupun white space.

array(['Kentucky', 'Maine', 'Massachusetts', 'Rhode Island', 'Oregon',
       'Wyoming', 'Montana', 'Louisiana', 'West Virginia', 'Missouri',
       'Arkansas', 'Hawaii', 'Delaware', 'New Hampshire', 'New York',
       'Alabama', 'Mississippi', 'North Carolina', 'California',
       'Oklahoma', 'Florida', 'Texas', 'Nevada', 'Kansas', 'Colorado',
       'North Dakota', 'Illinois', 'Indiana', 'Arizona', 'Alaska',
       'Tennessee', 'Ohio', 'New Jersey', 'Maryland', 'Vermont',
       'New Mexico', 'South Carolina', 'Idaho', 'Pennsylvania',
       'Connecticut', 'Utah', 'Virginia', 'Georgia', 'Nebraska', 'Iowa',
       'South Dakota', 'Minnesota', 'Washington', 'Wisconsin', 'Michigan'],
      dtype=object)

In [ ]:
df['Item Purchased'].unique() # menampilkan nilai unik pada column Item Purchased, untuk melakukan sample pengecekan nilai null maupun white space.

array(['Blouse', 'Sweater', 'Jeans', 'Sandals', 'Sneakers', 'Shirt',
       'Shorts', 'Coat', 'Handbag', 'Shoes', 'Dress', 'Skirt',
       'Sunglasses', 'Pants', 'Jacket', 'Hoodie', 'Jewelry', 'T-shirt',
       'Scarf', 'Hat', 'Socks', 'Backpack', 'Belt', 'Boots', 'Gloves'],
      dtype=object)

In [6]:
missing_counts = df.isnull().sum()
missing_percentage = (missing_counts / len(df) * 100)
missing_summary = pd.DataFrame ({'missing_counts': missing_counts, 'missing_percentage': missing_percentage})
print(missing_summary)

                          missing_counts  missing_percentage
Customer ID                            0                 0.0
Age                                    0                 0.0
Gender                                 0                 0.0
Item Purchased                         0                 0.0
Category                               0                 0.0
Purchase Amount (USD)                  0                 0.0
Location                               0                 0.0
Size                                   0                 0.0
Color                                  0                 0.0
Season                                 0                 0.0
Review Rating                          0                 0.0
Subscription Status                    0                 0.0
Payment Method                         0                 0.0
Shipping Type                          0                 0.0
Discount Applied                       0                 0.0
Promo Code Used                        0                 0.0
Previous Purchases                     0                 0.0
Preferred Payment Method               0                 0.0
Frequency of Purchases                 0                 0.0

Pengecekan jumlah Null dan presentasenya untuk pengecekan ulang.

In [ ]:
df.duplicated().sum() # mengecek jumlah data duplikat

0

In [8]:
df[df['Frequency of Purchases'] != df['Frequency of Purchases'].str.strip()]

Empty DataFrame
Columns: [Customer ID, Age, Gender, Item Purchased, Category, Purchase Amount (USD), Location, Size, Color, Season, Review Rating, Subscription Status, Payment Method, Shipping Type, Discount Applied, Promo Code Used, Previous Purchases, Preferred Payment Method, Frequency of Purchases]
Index: []

In [9]:
df[df['Preferred Payment Method'] != df['Preferred Payment Method'].str.strip()]

Empty DataFrame
Columns: [Customer ID, Age, Gender, Item Purchased, Category, Purchase Amount (USD), Location, Size, Color, Season, Review Rating, Subscription Status, Payment Method, Shipping Type, Discount Applied, Promo Code Used, Previous Purchases, Preferred Payment Method, Frequency of Purchases]
Index: []

In [10]:
df[df['Location'] != df['Location'].str.strip()]

Empty DataFrame
Columns: [Customer ID, Age, Gender, Item Purchased, Category, Purchase Amount (USD), Location, Size, Color, Season, Review Rating, Subscription Status, Payment Method, Shipping Type, Discount Applied, Promo Code Used, Previous Purchases, Preferred Payment Method, Frequency of Purchases]
Index: []

In [11]:
df[df['Category'] != df['Category'].str.strip()]

Empty DataFrame
Columns: [Customer ID, Age, Gender, Item Purchased, Category, Purchase Amount (USD), Location, Size, Color, Season, Review Rating, Subscription Status, Payment Method, Shipping Type, Discount Applied, Promo Code Used, Previous Purchases, Preferred Payment Method, Frequency of Purchases]
Index: []

In [12]:
df[df['Item Purchased'] != df['Item Purchased'].str.strip()]

Empty DataFrame
Columns: [Customer ID, Age, Gender, Item Purchased, Category, Purchase Amount (USD), Location, Size, Color, Season, Review Rating, Subscription Status, Payment Method, Shipping Type, Discount Applied, Promo Code Used, Previous Purchases, Preferred Payment Method, Frequency of Purchases]
Index: []

In [13]:
df[df['Gender'] != df['Gender'].str.strip()]

Empty DataFrame
Columns: [Customer ID, Age, Gender, Item Purchased, Category, Purchase Amount (USD), Location, Size, Color, Season, Review Rating, Subscription Status, Payment Method, Shipping Type, Discount Applied, Promo Code Used, Previous Purchases, Preferred Payment Method, Frequency of Purchases]
Index: []

Pengecekan data yang mengandung white space.

# Transform

In [ ]:
df.dtypes # mengecek tipe data pada setiap column

Customer ID                   int64
Age                           int64
Gender                       object
Item Purchased               object
Category                     object
Purchase Amount (USD)         int64
Location                     object
Size                         object
Color                        object
Season                       object
Review Rating               float64
Subscription Status          object
Payment Method               object
Shipping Type                object
Discount Applied             object
Promo Code Used              object
Previous Purchases            int64
Preferred Payment Method     object
Frequency of Purchases       object
dtype: object

In [ ]:
df['Customer ID'] = df['Customer ID'].astype('str') # mengubah tipe data menjadi string pada column Customer ID

In [ ]:
df['Subscription Status'] = df['Subscription Status'].replace({'Yes': True, 'No': False}).astype(bool)
df['Discount Applied'] = df['Discount Applied'].replace({'Yes': True, 'No': False}).astype(bool)
df['Promo Code Used'] = df['Promo Code Used'].replace({'Yes': True, 'No': False}).astype(bool)
# mengubah nilai 'Yes' menjadi True dan 'No' menjadi False pada column Subscription Status, Discount Applied, dan Promo Code Used, kemudian mengubah tipe data menjadi boolean (bool) pada ketiga column tersebut.

C:\Users\User\AppData\Local\Temp\ipykernel_21876\346592153.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Subscription Status'] = df['Subscription Status'].replace({'Yes': True, 'No': False}).astype(bool)
C:\Users\User\AppData\Local\Temp\ipykernel_21876\346592153.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Discount Applied'] = df['Discount Applied'].replace({'Yes': True, 'No': False}).astype(bool)
C:\Users\User\AppData\Local\Temp\ipykernel_21876\346592153.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Promo Code Used'] = df['Promo Code Used'].replace({'Yes': True, 'No': False}).astype(bool)

In [ ]:
df.dtypes # data berhasil diubah

Customer ID                  object
Age                           int64
Gender                       object
Item Purchased               object
Category                     object
Purchase Amount (USD)         int64
Location                     object
Size                         object
Color                        object
Season                       object
Review Rating               float64
Subscription Status            bool
Payment Method               object
Shipping Type                object
Discount Applied               bool
Promo Code Used                bool
Previous Purchases            int64
Preferred Payment Method     object
Frequency of Purchases       object
dtype: object

In [ ]:
df # menampilkan data df setelah dilakukan data cleaning

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,True,Credit Card,Express,True,True,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,True,Bank Transfer,Express,True,True,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,True,Cash,Free Shipping,True,True,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,True,PayPal,Next Day Air,True,True,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,True,Cash,Free Shipping,True,True,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,False,Cash,2-Day Shipping,False,False,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,False,PayPal,Store Pickup,False,False,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,False,Credit Card,Standard,False,False,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,False,PayPal,Express,False,False,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,False,Bank Transfer,Store Pickup,False,False,33,Venmo,Quarterly

In [ ]:
df.to_csv('data_cleaned.csv', index=False)
# menyimpan data df yang sudah dibersihkan ke dalam file csv dengan nama data_cleaned.csv.

# Great Expectations

In [ ]:
from great_expectations.data_context import FileDataContext # import lib GX yang diperlukan.

context = FileDataContext.create(project_root_dir='./') # untuk membuat GX context yang berbentuk folder bernama gx.

In [ ]:
datasource_name = 'shop_trend_nov_9_min_1' # memberikan nama pada Datasource.
datasource = context.sources.add_pandas(datasource_name)

asset_name = 'shop_trend_nov' # memberikan nama pada asset.
path_to_data = 'data_cleaned.csv' # mengambil data dari file csv bernama data_cleaned.csv, kemudian disimpan pada variabel path_to_data.
asset = datasource.add_csv_asset(asset_name, filepath_or_buffer=path_to_data) # syntax untuk meng-load/register path data 


batch_request = asset.build_batch_request() # untuk membaca datanya

In [ ]:

expectation_suite_name = 'expectation-shoptrends-dataset' # memberikan nama pada suite dengan nama expectation-shoptrends-dataset.
context.add_or_update_expectation_suite(expectation_suite_name) # membuat expectation suite.

validator = context.get_validator( 
    batch_request = batch_request,
    expectation_suite_name = expectation_suite_name
) # untuk menyambungkan suite ke data yang telah dibaca/akan digunakan.

validator.head() # menampilkan data (5 teratas).

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,True,Credit Card,Express,True,True,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,True,Bank Transfer,Express,True,True,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,True,Cash,Free Shipping,True,True,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,True,PayPal,Next Day Air,True,True,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,True,Cash,Free Shipping,True,True,31,PayPal,Annually

In [25]:
# Expectation 1 : Column `Customer ID` harus unique

validator.expect_column_values_to_be_unique('Customer ID')

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 3900,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [26]:
# Expectation 2 : Column `Age` harus berada di antara 1 sampai 110

validator.expect_column_values_to_be_between(
    column='Age', min_value=1, max_value=110
)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 3900,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [ ]:
# Expectation 3 : Column `Payment Method` harus mengandung salah satu dari 6 hal berikut:
# Credit Card
# Bank Transfer
# Cash
# PayPal
# Venmo
# Debit Card

validator.expect_column_values_to_be_in_set('Payment Method', ['Credit Card', 'Bank Transfer', 'Cash', 'PayPal', 'Venmo',
       'Debit Card'])

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 3900,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [28]:
# Expectation 4 : Column `Discount Applied` harus dalam bentuk tipe boolean.

validator.expect_column_values_to_be_of_type(
    "Discount Applied",
    "bool"
)

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "observed_value": "bool_"
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [29]:
# Expectation 5 : Column `Review Rating` harus memiliki nilai median antara 1 sampai 5.

validator.expect_column_median_to_be_between(
    column="Review Rating",
    min_value=1,
    max_value=5
)

Calculating Metrics:   0%|          | 0/4 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "observed_value": 3.7
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [30]:
# Expectation 6 : Column `Purchase Amount (USD)` harus memiliki nilai mean antara 50 sampai 150.

validator.expect_column_mean_to_be_between(
    column="Purchase Amount (USD)",
    min_value=50,
    max_value=150
)

Calculating Metrics:   0%|          | 0/4 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "observed_value": 59.76435897435898
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [ ]:
# Expectation 7 : Column `Category` harus memiliki pasangan nilai yang benar dengan column `Item Purchased`.

validator.expect_column_pair_values_to_be_in_set(
        'Category',
        'Item Purchased',
        [
            ('Clothing','Blouse'),
            ('Clothing','Dress'),
            ('Clothing','Hoodie'),
            ('Clothing','Jeans'),
            ('Clothing','Pants'),
            ('Clothing','Shirt'),
            ('Clothing','Shorts'),
            ('Clothing','Skirt'),            
            ('Clothing','Socks'),
            ('Clothing','Sweater'),
            ('Clothing','T-shirt'),
            ('Accessories','Backpack'),            
            ('Accessories','Belt'),
            ('Accessories','Gloves'),
            ('Accessories','Handbag'),
            ('Accessories','Hat'),            
            ('Accessories','Jewelry'),
            ('Accessories','Scarf'),
            ('Accessories','Sunglasses'),
            ('Accessories','yellow'),            
            ('Footwear','Boots'),
            ('Footwear','Sandals'),
            ('Footwear','Sneakers'),
            ('Footwear','Shoes'),            
            ('Outerwear','Coat'),
            ('Outerwear','Jacket'),  
        ]
)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 3900,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [ ]:
validator.save_expectation_suite(discard_failed_expectations=False)
# save validator tersebut ke dalam suite.

In [ ]:
checkpoint_1 = context.add_or_update_checkpoint(
    name = 'checkpoint_1',
    validator = validator,
)
# membuat checkpoint.

In [ ]:
checkpoint_result = checkpoint_1.run() # menjalankan checkpoint 1.

Calculating Metrics:   0%|          | 0/35 [00:00<?, ?it/s]

In [ ]:
context.build_data_docs()
# membuat data docs.

{'local_site': 'file://c:\\Users\\User\\Documents\\coda_16\\p2-coda016-rmt-m3-kurniasuryab13\\gx\\uncommitted/data_docs/local_site/index.html'}